version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker build -t sowrongimright/docker-react-test -f Dockerfile.dev .
      - run: docker run sowrongimright/docker-react-test npm run test
      - store_artifacts:
        path: ~/repo/artifacts