name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sowrongimright/docker-react-test@master
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD1}}
      - run: docker build -t sowrongimright/react-docker-test -f Dockerfile.dev .
      - run: docker run -e CI=true sowrongimright/react-docker-test npm test